# Generated by Django 2.0.1 on 2018-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_title', models.CharField(max_length=1000)),
                ('proj_title', models.CharField(max_length=1000)),
                ('stud_title', models.CharField(max_length=1000)),
                ('prog_lead', models.CharField(max_length=300)),
                ('stud_lead', models.CharField(max_length=300)),
                ('co_res', models.TextField()),
                ('res_site', models.TextField()),
                ('campus', models.CharField(max_length=50)),
                ('category_res', models.CharField(max_length=50)),
                ('classif_res', models.CharField(max_length=50)),
                ('amt_granted', models.TextField()),
                ('date_started', models.DateField()),
                ('res_status', models.CharField(max_length=10)),
                ('date_completed', models.DateField()),
                ('res_SF', models.TextField()),
                ('res_pubstat', models.CharField(max_length=5)),
                ('res_JN', models.TextField()),
                ('res_JV', models.CharField(max_length=100)),
                ('date_pub', models.DateField()),
                ('res_iprstat', models.CharField(max_length=5)),
                ('apptype', models.CharField(max_length=100)),
                ('date_appl', models.DateField()),
                ('date_pprv', models.DateField()),
                ('app_pending', models.CharField(max_length=5)),
                ('res_abs', models.TextField()),
            ],
        ),
    ]
