# Generated by Django 2.0.1 on 2018-01-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_res',
            name='app_pending',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='res_abs',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='res_iprstat',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='res_pubstat',
            field=models.BooleanField(),
        ),
    ]
