# Generated by Django 2.0.1 on 2018-01-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIS', '0002_auto_20180121_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_res',
            name='res_status',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10),
        ),
    ]
