# Generated by Django 2.0.1 on 2018-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIS', '0003_auto_20180121_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_res',
            name='app_pending',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='apptype',
            field=models.CharField(choices=[('PATENT', 'Patent'), ('UTILITY_MODEL', 'Utility Model'), ('TRADEMARK_TRADENAME', 'Trademark/Tradename'), ('COPYRIGHT', 'Copyright'), ('OTHER', 'Other')], default='PATENT', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='campus',
            field=models.CharField(choices=[('APARRI', 'Aparri'), ('LASAM', 'Lasam'), ('LALLO', 'Lal-lo'), ('SANCHEZ_MIRA', 'Sanchez Mira'), ('CARIG', 'Carig'), ('ANDREWS', 'Andrews'), ('PIAT', 'Piat')], default='ANDREWS', max_length=50),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='category_res',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('APPLIED', 'Applied'), ('PILOT_TESTING', 'Pilot Testing'), ('TECHNOLOGY_PROMOTION_COMMERCIALIZATION', 'Technology Promotion / Commercialization')], default='BASIC', max_length=50),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='classif_res',
            field=models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('BIOTECHNOLOGY', 'Biotechnology'), ('ICT', 'ICT'), ('HEALTH_PRODUCTS', 'Health Products'), ('ALTERNATIVE_ENERGY', 'Alternative Energy'), ('CLIMATE_CHANGE', 'Climate Change'), ('ENVIRONMENT', 'Environment'), ('SOCIO_ECONOMIC', 'Socio-economic'), ('NATURAL_PRODUCTS', 'Natural Products'), ('OTHER', 'Other')], default='ICT', max_length=50),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='res_SF',
            field=models.TextField(choices=[('CSU', 'CSU'), ('CHED', 'CHED'), ('DA_BAR', 'DA-BAR'), ('DOST', 'DOST'), ('PCCARRD', 'PCCARRD'), ('PCIERD', 'PCIERD'), ('PCHRD', 'PCHRD'), ('DA', 'DA'), ('OTHER', 'Other')], default='CSU'),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='res_iprstat',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='res_pubstat',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=5),
        ),
        migrations.AlterField(
            model_name='list_of_res',
            name='res_status',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10),
        ),
    ]
